# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16XNuI4sVaPAy4gZjLDFAj9MQBJj5qxXX
"""

import os
import zipfile
import glob
import shutil
import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import drive, files

# --- Configuration ---
# IMPORTANT: Provide the path to your ZIP file in Google Drive
zip_file_path = "/content/archive.zip"  # @param {type:"string"}

# Desired colormap for RGB conversion (choose from 'TURBO', 'JET', 'INFERNO', 'RAINBOW', 'HSV')
colormap_choice = 'TURBO' # @param ['TURBO', 'JET', 'INFERNO', 'RAINBOW', 'HSV'] {type:"string"}

# Define working directories
WORKING_DIR = 'infrared_processing_temp'
RESULTS_DIR = os.path.join(WORKING_DIR, 'results')

# Ensure colormap is valid
COLORMAPS = {
    'TURBO': cv2.COLORMAP_TURBO,
    'JET': cv2.COLORMAP_JET,
    'INFERNO': cv2.COLORMAP_INFERNO,
    'RAINBOW': cv2.COLORMAP_RAINBOW,
    'HSV': cv2.COLORMAP_HSV
}

if colormap_choice not in COLORMAPS:
    raise ValueError(f"Invalid colormap choice: {colormap_choice}. Must be one of {list(COLORMAPS.keys())}")

SELECTED_COLORMAP = COLORMAPS[colormap_choice]

# --- Google Drive Mounting ---
print("Mounting Google Drive...")
drive.mount('/content/drive', force_remount=True)
print("Google Drive mounted successfully.")

# --- Helper Functions ---

def setup_directories():
    """Creates necessary working and output directories."""
    if os.path.exists(WORKING_DIR):
        shutil.rmtree(WORKING_DIR)
    os.makedirs(WORKING_DIR)

    os.makedirs(os.path.join(RESULTS_DIR, 'clahe'))
    os.makedirs(os.path.join(RESULTS_DIR, 'sharpened'))
    os.makedirs(os.path.join(RESULTS_DIR, 'rgb'))
    os.makedirs(os.path.join(RESULTS_DIR, 'comparisons'))
    print(f"Created working directory: {WORKING_DIR}")
    print(f"Created results directories inside: {RESULTS_DIR}")

def extract_zip(zip_path, extract_to_dir):
    """Extracts a ZIP file to a specified directory."""
    if not os.path.exists(zip_path):
        raise FileNotFoundError(f"ZIP file not found at: {zip_path}")

    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        zip_ref.extractall(extract_to_dir)
    print(f"ZIP file extracted to: {extract_to_dir}")

def detect_image_files(directory):
    """Detects common image files (jpg, png, bmp, tif) in a directory."""
    image_extensions = ['*.jpg', '*.jpeg', '*.png', '*.bmp', '*.tif', '*.tiff']
    image_paths = []
    for ext in image_extensions:
        image_paths.extend(glob.glob(os.path.join(directory, '**', ext), recursive=True))
    if not image_paths:
        raise ValueError("No image files found in the extracted directory.")
    print(f"Detected {len(image_paths)} image(s).")
    return sorted(image_paths)

def load_and_preprocess_image(image_path):
    """Loads an image and converts it to grayscale if it isn't already."""
    img = cv2.imread(image_path, cv2.IMREAD_UNCHANGED)
    if img is None:
        raise ValueError(f"Could not load image: {image_path}")

    if len(img.shape) == 3:
        # Convert to grayscale if it's a color image
        gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    else:
        # Image is already grayscale
        gray_img = img

    # Ensure 8-bit for CLAHE and other operations if it's not already
    if gray_img.dtype != np.uint8:
        gray_img = cv2.normalize(gray_img, None, 0, 255, cv2.NORM_MINMAX).astype(np.uint8)

    return img, gray_img

def apply_clahe(image):
    """Applies Contrast Limited Adaptive Histogram Equalization (CLAHE)."""
    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8,8))
    clahe_enhanced = clahe.apply(image)
    return clahe_enhanced

def apply_sharpening(image):
    """Applies a sharpening filter to the image."""
    # Define the sharpening kernel
    kernel = np.array([[-1, -1, -1],
                       [-1,  9, -1],
                       [-1, -1, -1]])
    sharpened = cv2.filter2D(image, -1, kernel)
    return sharpened

def colorize_image(grayscale_image, colormap):
    """Converts a grayscale image to a pseudo-colored RGB image using a colormap."""
    # Ensure image is 8-bit for applyColorMap
    if grayscale_image.dtype != np.uint8:
        grayscale_image = cv2.normalize(grayscale_image, None, 0, 255, cv2.NORM_MINMAX).astype(np.uint8)

    rgb_image = cv2.applyColorMap(grayscale_image, colormap)
    return rgb_image

def save_image(image, output_path, filename, folder_name):
    """Saves an image to the specified output folder."""
    full_path = os.path.join(RESULTS_DIR, folder_name, f"{filename}.png")
    os.makedirs(os.path.dirname(full_path), exist_ok=True)
    cv2.imwrite(full_path, image)
    print(f"Saved {filename}.png to {os.path.join(folder_name, f'{filename}.png')}")
    return full_path

def display_comparison(original_img, clahe_img, sharpened_img, rgb_img, title_prefix):
    """Creates and displays a comparison figure of the processing steps."""
    fig, axes = plt.subplots(1, 4, figsize=(20, 5))
    fig.suptitle(f"Image Processing Steps: {title_prefix}", fontsize=16)

    # Convert original to RGB if it's BGR for proper display with matplotlib
    if len(original_img.shape) == 3:
        original_display = cv2.cvtColor(original_img, cv2.COLOR_BGR2RGB)
    else:
        original_display = original_img # Grayscale

    axes[0].imshow(original_display, cmap='gray')
    axes[0].set_title('Original Infrared Image')
    axes[0].axis('off')

    axes[1].imshow(clahe_img, cmap='gray')
    axes[1].set_title('CLAHE Enhanced Image')
    axes[1].axis('off')

    axes[2].imshow(sharpened_img, cmap='gray')
    axes[2].set_title('Sharpened Image')
    axes[2].axis('off')

    # OpenCV's applyColorMap outputs BGR, convert to RGB for matplotlib
    rgb_display = cv2.cvtColor(rgb_img, cv2.COLOR_BGR2RGB)
    axes[3].imshow(rgb_display)
    axes[3].set_title(f'RGB Colorized ({colormap_choice})')
    axes[3].axis('off')

    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    plt.show()

    # Save the comparison figure
    comparison_filename = f"{title_prefix}_comparison.png"
    plt.savefig(os.path.join(RESULTS_DIR, 'comparisons', comparison_filename))
    plt.close(fig) # Close the figure to free up memory
    print(f"Saved comparison figure to {os.path.join('comparisons', comparison_filename)}")

def perform_analysis(image, title_prefix):
    """Displays image statistics and plots the histogram."""
    print(f"\n--- Analysis for: {title_prefix} ---")
    height, width = image.shape[:2]
    print(f"Dimensions: {width}x{height}")

    mean_intensity = np.mean(image)
    min_intensity = np.min(image)
    max_intensity = np.max(image)
    std_dev = np.std(image)

    print(f"Mean Pixel Intensity: {mean_intensity:.2f}")
    print(f"Minimum Intensity: {min_intensity}")
    print(f"Maximum Intensity: {max_intensity}")
    print(f"Standard Deviation: {std_dev:.2f}")

    # Plot histogram
    plt.figure(figsize=(10, 4))
    plt.subplot(1, 2, 1)
    plt.hist(image.flatten(), bins=256, range=[0, 256], color='gray', alpha=0.7)
    plt.title(f'Histogram for {title_prefix}')
    plt.xlabel('Pixel Intensity')
    plt.ylabel('Frequency')

    # Placeholder for 'Enhanced histogram' - will plot CLAHE for comparison
    # This assumes 'image' is the original grayscale for the first histogram
    # The second histogram will be generated below inside the main loop for CLAHE
    plt.tight_layout()
    plt.show()

def create_results_zip(source_dir, output_zip_path):
    """Creates a ZIP archive of the results folder."""
    shutil.make_archive(output_zip_path.replace('.zip', ''), 'zip', source_dir)
    print(f"Created results ZIP file: {output_zip_path}")

    # Move to Google Drive
    drive_output_path = os.path.join('/content/drive/MyDrive', os.path.basename(output_zip_path))
    shutil.move(output_zip_path, drive_output_path)
    print(f"Moved results ZIP to Google Drive: {drive_output_path}")
    return drive_output_path

# --- Main Processing Logic ---
def main():
    setup_directories()

    # Extract ZIP file contents to the working directory
    extracted_dir = os.path.join(WORKING_DIR, 'extracted_images')
    os.makedirs(extracted_dir, exist_ok=True)
    extract_zip(zip_file_path, extracted_dir)

    # Detect image files in the extracted directory
    image_files = detect_image_files(extracted_dir)

    for i, image_path in enumerate(image_files):
        base_filename = os.path.splitext(os.path.basename(image_path))[0]
        print(f"\n--- Processing Image {i+1}/{len(image_files)}: {base_filename} ---")

        # 1. Load and convert to grayscale
        original_bgr, original_grayscale = load_and_preprocess_image(image_path)
        # saving original grayscale is optional, currently commented out as in original
        # save_image(original_grayscale, RESULTS_DIR, f"{base_filename}_original_grayscale", "clahe")

        # 2. Apply CLAHE (still computed for analysis and comparison, but not for the final colored image chain)
        clahe_enhanced = apply_clahe(original_grayscale)
        save_image(clahe_enhanced, RESULTS_DIR, f"{base_filename}_clahe_enhanced", "clahe")

        # 3. Apply Sharpening directly to the original grayscale image
        sharpened_grayscale_output = apply_sharpening(original_grayscale)
        save_image(sharpened_grayscale_output, RESULTS_DIR, f"{base_filename}_sharpened_image_from_original", "sharpened")

        # 4. Colorize the newly sharpened grayscale image
        rgb_final_output = colorize_image(sharpened_grayscale_output, SELECTED_COLORMAP)
        save_image(rgb_final_output, RESULTS_DIR, f"{base_filename}_rgb_output_from_sharpened_original", "rgb")

        # 5. Visualization: Display original, CLAHE, sharpened (from original), and colorized (from sharpened original)
        display_comparison(original_bgr, clahe_enhanced, sharpened_grayscale_output, rgb_final_output, base_filename)

        # 6. Analysis
        perform_analysis(original_grayscale, f"{base_filename} - Original Grayscale")

        # Plot enhanced histogram for comparison
        plt.figure(figsize=(5, 4))
        plt.hist(clahe_enhanced.flatten(), bins=256, range=[0, 256], color='blue', alpha=0.7)
        plt.title(f'Histogram for {base_filename} - CLAHE Enhanced')
        plt.xlabel('Pixel Intensity')
        plt.ylabel('Frequency')
        plt.tight_layout()
        plt.show()

    # 7. Create final ZIP and move to Google Drive
    final_zip_name = 'infrared_processing_results.zip'
    drive_zip_path = create_results_zip(WORKING_DIR, final_zip_name) # Changed RESULTS_DIR to WORKING_DIR to include all subfolders of RESULTS_DIR

    print("\n--- Processing Complete ---")
    print(f"All processed results are available in a ZIP file at: {drive_zip_path}")
    print("You can also download it directly from Colab using the link below:")

    # Provide code to download the ZIP file from Colab
    files.download(drive_zip_path)

# Run the main function
if __name__ == '__main__':
    main()